/*1. What are the names of all the countries in the country table?*/

SELECT country_name
FROM country ;

/*2. What is the total number of customers in the customers table?*/

SELECT count(distinct customer_id) as Totalcustomer
FROM customers ;


/*3. What is the average age of customers who can 
receive marketing emails (can_email is set to 'yes')?*/

SELECT round(avg(age)) as Average_age
FROM customers
WHERE can_email = 'yes' ;



/*4. How many orders were made by customers aged 30 or older?*/

SELECT  count(orders.order_id) as Totalorders
FROM orders
JOIN customers on customers.customer_id = orders.customer_id
WHERE customers.age >= 30 ;


/*5.What is the total revenue generated by each product category?*/

SELECT p.category, SUM(p.price) AS total_revenue
FROM products p
INNER JOIN baskets b ON p.product_id = b.product_id
INNER JOIN orders o ON b.order_id = o.order_id
GROUP BY p.category
ORDER BY total_revenue DESC;

/*6.What is the average price of products in the 'food' category?*/

SELECT round(avg(price),2) as Average_price
FROM products 
WHERE category = "food" ;

/*7.How many orders were made in each sales channel (sales_channel column) in the orders table?*/

SELECT sales_channel , count(*) As Total_orders
FROM orders
GROUP BY sales_channel ;



/*8.What is the date of the latest order made by a customer who can receive marketing emails?*/

SELECT o.date_shop 
FROM customers c
INNER JOIN orders o using (customer_id)
WHERE c.can_email = 'Yes' 
order by o.date_shop desc limit 1;

/*9.What is the name of the country with the highest number of orders?*/

SELECT c.country_name
FROM country c
JOIN (
    SELECT country_id, COUNT(*) AS order_count
    FROM orders
    GROUP BY country_id
    ORDER BY order_count DESC
    LIMIT 1
) AS max_orders ON c.country_id = max_orders.country_id;

/*10.What is the average age of customers who made orders in the 'vitamins' product category?*/

SELECT round(AVG(c.age)) AS average_age
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN baskets b ON o.order_id = b.order_id
INNER JOIN products p ON b.product_id = p.product_id
WHERE p.category = 'vitamins';
